server:
  port: 8080

spring:
  profiles:
    active: dev

  application:
    name: laolao-code

  datasource:
    driver-class-name: ${datasource.driver-class-name}
    url: jdbc:mysql://${datasource.host}:${datasource.port}/${datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: ${datasource.username}
    password: ${datasource.password}

  data:
    redis:
      host: ${redis.host}
      port: ${redis.port}
      database: ${redis.database}

  ai:
    deepseek:
      base-url: https://api.deepseek.com/
      api-key: ${ai.deepseek.api-key}

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  # 设置jwt签名加密时使用的秘钥
  user-secret-key: ${jwt.user-secret-key}
  # 设置jwt过期时间
  user-ttl: ${jwt.user-ttl}